name = "vlp-onboarding-worker"
main = "workers/src/index.js"
compatibility_date = "2026-03-20"
type = "javascript"

[[r2_buckets]]
binding = "ONBOARDING_R2"
bucket_name = "onboarding-records"
preview_bucket_name = "onboarding-records"
